version: '3'

services:
  eda:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "9000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: edanalytica_quiz
    ports:
      - "3308:3306"
    volumes:
      - "./data:/var/lib/mysql:rw"
      - "./my.conf:/etc/mysql/conf.d/config-file.cnf"
  webserver:
    image: nginx:alpine
    volumes:
      - "./templates/edAnalyticaHtml:/usr/share/nginx/html"
    ports:
      - "9001:80"
  admin:
    image: adminer
    ports:
      - "8080:8080"
