# Generated by Django 3.0 on 2019-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpool',
            name='answer',
            field=models.TextField(default=None, max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionpool',
            name='explanation',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
