# Generated by Django 3.0 on 2019-12-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20191213_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(max_length=4000)),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionpool',
            name='answer',
        ),
        migrations.DeleteModel(
            name='QuestionOptions',
        ),
        migrations.AddField(
            model_name='mcqoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.QuestionPool'),
        ),
    ]
