# Generated by Django 3.0 on 2019-12-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191214_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpool',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.QuestionType'),
        ),
    ]
