# Generated by Django 3.0 on 2019-12-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_submissionmeta_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmeta',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Quiz'),
            preserve_default=False,
        ),
    ]
