# Generated by Django 3.0 on 2019-12-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_submissionmeta_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='answer',
            field=models.PositiveIntegerField(),
        ),
    ]
