# Generated by Django 3.0.2 on 2020-01-25 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_submissions_is_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmissionCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='submissionmeta',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionmeta',
            name='submitted_on',
            field=models.DateTimeField(),
        ),
    ]
