# Generated by Django 3.0.2 on 2020-01-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200125_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmeta',
            name='submitted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
