# Generated by Django 3.0.2 on 2020-01-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='users',
        ),
        migrations.AddField(
            model_name='org',
            name='footer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='org_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
